// Regenerates bin/rs_assets.py from assets/logo-light.svg. The dashboard is dark-only, so the
// light-ink variant is the one it inlines: LOGO stays an SVG (crisp at any DPI); FAVICON is a
// PNG tile because tab icons need an opaque ground and pixel output. `pnpm brand` to run.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { tile } from "./tile.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const svgPath = join(root, "assets", "logo-light.svg");
const out = join(root, "bin", "rs_assets.py");

const svg = await readFile(svgPath, "utf8");
const logo = `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
const fav = await tile(sharp, svg, 48, { radius: 10, inner: 0.78 });
const favicon = `data:image/png;base64,${fav.toString("base64")}`;

await writeFile(
  out,
  `"""rs_assets.py — inlined brand assets (data URIs), imported by the server.

LOGO is the header/sidebar/sign-in mark: the light-ink ReviewStage mark (assets/logo-light.svg)
inlined as SVG so it stays crisp at any DPI on the dark UI. FAVICON is a 48px PNG of the same
mark on a rounded #171922 tile. Generated by dashboard-ui/scripts/brand.mjs (\`pnpm brand\`);
do not hand-edit."""

LOGO = "${logo}"

FAVICON = "${favicon}"
`,
);
console.log(`rs_assets.py <- ${svgPath} (logo ${svg.length}B svg, favicon ${fav.length}B png)`);
