import { fileURLToPath } from "node:url";
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";

const site = "https://wimukti.github.io";
const base = "/reviewstage";
// The site renders the app's own components (design.md §7): `@app/…` is dashboard-ui/src,
// reached by path rather than a workspace so the Docker and CI install paths stay untouched.
const appSrc = fileURLToPath(new URL("../dashboard-ui/src", import.meta.url));

export default defineConfig({
  site,
  base,
  output: "static",
  trailingSlash: "always",
  // Team mode moved from Start to Guides; links in the wild and the app's login page keep working.
  redirects: { "/start/team-mode/": `${base}/guides/team-mode/` },
  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: { "@app": appSrc, "@": appSrc },  // "@" is the app's own alias (shadcn imports @/lib/utils)
      // Bare imports inside dashboard-ui/src resolve from THAT directory's node_modules, which
      // the site's CI job never installs — so the build broke on `radix-ui` from button.tsx.
      // dedupe pins every package the app's source imports to the site's own copy.
      dedupe: ["react", "react-dom", "radix-ui", "lucide-react", "class-variance-authority",
               "clsx", "tailwind-merge", "cmdk", "react-markdown", "remark-gfm"],
    },
    server: { fs: { allow: [".", appSrc] } },
  },
  integrations: [
    react(),
    // stage-proof is the island's proof page (design §7), not a page for readers.
    sitemap({ filter: (page) => !page.includes("/stage-proof/") }),
    starlight({
      title: "ReviewStage",
      description:
        "ReviewStage drafts your PR review from the real diff, on your own Claude plan, and stages every finding privately. Nothing posts until you click.",
      favicon: "/favicon.svg",
      head: [
        { tag: "link", attrs: { rel: "icon", href: `${base}/favicon.ico`, sizes: "16x16 32x32 48x48" } },
        { tag: "link", attrs: { rel: "icon", type: "image/png", sizes: "192x192", href: `${base}/favicon-192.png` } },
        { tag: "link", attrs: { rel: "icon", type: "image/png", sizes: "512x512", href: `${base}/favicon-512.png` } },
        { tag: "link", attrs: { rel: "apple-touch-icon", sizes: "180x180", href: `${base}/apple-touch-icon.png` } },
        { tag: "meta", attrs: { name: "theme-color", media: "(prefers-color-scheme: light)", content: "#F6F6F9" } },
        { tag: "meta", attrs: { name: "theme-color", media: "(prefers-color-scheme: dark)", content: "#0B0C10" } },
        { tag: "meta", attrs: { property: "og:image", content: `${site}${base}/og.png` } },
        { tag: "meta", attrs: { property: "og:image:width", content: "1200" } },
        { tag: "meta", attrs: { property: "og:image:height", content: "630" } },
        { tag: "meta", attrs: { name: "twitter:card", content: "summary_large_image" } },
        { tag: "meta", attrs: { name: "twitter:image", content: `${site}${base}/og.png` } },
      ],
      customCss: ["./src/styles/app.css"],
      components: {
        ThemeProvider: "./src/components/starlight/ThemeProvider.astro",
        SiteTitle: "./src/components/starlight/SiteTitle.astro",
        Footer: "./src/components/starlight/Footer.astro",
        ThemeSelect: "./src/components/starlight/ThemeSelect.astro",
      },
      expressiveCode: {
        themes: ["github-dark-default", "github-light"],
        useStarlightUiThemeColors: true,
        // data-theme carries the *choice* ("dark", "light", "system"); the resolved scheme is
        // stamped beside it as data-resolved (scripts/theme.ts), so a light-system machine gets
        // the light code theme too. Starlight's own switch keys on data-theme alone.
        themeCssSelector: (theme) => `[data-resolved='${theme.type}']`,
        styleOverrides: { borderRadius: "12px", codeFontFamily: "var(--mono)" },
      },
      editLink: { baseUrl: "https://github.com/Wimukti/reviewstage/edit/main/website/" },
      lastUpdated: true,
      social: [
        { icon: "github", label: "ReviewStage on GitHub", href: "https://github.com/Wimukti/reviewstage" },
      ],
      // Start is spelled out so Team workflow (a guide by directory) sits where a new reader
      // looks for it; the guide is hidden from the autogenerated Guides group for that reason.
      sidebar: [
        { label: "Home", link: "/" },
        {
          label: "Start here",
          items: [
            { label: "What you get", link: "/start/" },
            { label: "Install", link: "/start/install/" },
            { label: "First review", link: "/start/first-review/" },
            { label: "Team workflow", link: "/guides/team-workflow/" },
          ],
        },
        { label: "Guides", autogenerate: { directory: "guides" } },
        {
          label: "Operations",
          items: [
            { label: "Configuration", link: "/operations/configuration/" },
            { label: "FAQ", link: "/operations/faq/" },
            { label: "Troubleshooting", link: "/operations/troubleshooting/" },
          ],
        },
        { label: "Security", autogenerate: { directory: "security" } },
        { label: "Developers", autogenerate: { directory: "developers" } },
      ],
    }),
  ],
});
